# Generated by Django 6.0.2 on 2026-09-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LinguisticTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("morfosintaxis", "Morfosintaxis"),
                            ("sintaxis", "Sintaxis"),
                            ("semantica", "Semántica"),
                            ("morfologia", "Morfología"),
                            ("ortografia", "Ortografía"),
                            ("fonetica", "Fonética"),
                            ("fonologia", "Fonología"),
                            ("gramatica", "Gramática"),
                            ("retorica", "Retórica"),
                            ("literatura", "Literatura"),
                            ("redaccion", "Redacción"),
                            ("etimologia", "Etimología"),
                            ("puntuacion", "Puntuación"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subcategory", models.CharField(blank=True, max_length=100)),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A1", "A1 - Principiante"),
                            ("A2", "A2 - Básico"),
                            ("B1", "B1 - Intermedio"),
                            ("B2", "B2 - Intermedio Alto"),
                            ("C1", "C1 - Avanzado"),
                            ("C2", "C2 - Experto"),
                        ],
                        max_length=10,
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=50)),
                ("technique_type", models.CharField(blank=True, max_length=50)),
                ("content", models.JSONField(default=dict)),
                ("theory", models.TextField(blank=True)),
                ("example", models.TextField(blank=True)),
                (
                    "exercise_text",
                    models.TextField(blank=True, verbose_name="Ejercicio"),
                ),
                ("correct_answer", models.TextField(blank=True)),
                ("difficulty", models.IntegerField(default=1)),
                ("points", models.IntegerField(default=10)),
                ("tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["category", "level"],
                        name="content_lin_categor_bbd316_idx",
                    ),
                    models.Index(
                        fields=["technique_type"], name="content_lin_techniq_256cc7_idx"
                    ),
                ],
            },
        ),
    ]
