# Generated by Django 6.0.2 on 2026-09-07 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_curso_evaluacion_leccion_ejercicio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                ("codigo", models.CharField(max_length=100, unique=True)),
                ("puntaje_final", models.FloatField()),
                ("url_pdf", models.URLField(blank=True, null=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to="content.curso",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgresoEstudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lecciones_completadas", models.IntegerField(default=0)),
                ("ejercicios_completados", models.IntegerField(default=0)),
                ("ejercicios_correctos", models.IntegerField(default=0)),
                ("puntaje_total", models.IntegerField(default=0)),
                ("porcentaje_completado", models.FloatField(default=0.0)),
                ("ultimo_acceso", models.DateTimeField(auto_now=True)),
                ("completado", models.BooleanField(default=False)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresos",
                        to="content.curso",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("estudiante", "curso")},
            },
        ),
        migrations.CreateModel(
            name="RespuestaEjercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respuesta_dada", models.TextField()),
                ("es_correcta", models.BooleanField(default=False)),
                ("puntaje_obtenido", models.IntegerField(default=0)),
                ("intentos", models.IntegerField(default=1)),
                ("tiempo_segundos", models.IntegerField(default=0)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "ejercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="content.ejercicio",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("estudiante", "ejercicio")},
            },
        ),
    ]
