# Generated by Django 6.0.2 on 2026-02-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Programa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CPP", "C++"),
                            ("PY", "Python"),
                            ("JS", "JavaScript"),
                        ],
                        max_length=3,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
    ]
