# Generated by Django 6.0.2 on 2026-02-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="usuario",
            name="es_profesor",
            field=models.BooleanField(default=False),
        ),
    ]
