# Generated by Django 6.0.2 on 2026-02-09 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecuenciaDidactica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "objetivo_general",
                    models.TextField(help_text="¿Qué logrará el alumno al terminar?"),
                ),
                ("introduccion", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "programa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secuencia",
                        to="core.programa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Creador de Contenido",
                "verbose_name_plural": "Configurador de Secuencias",
            },
        ),
    ]
