# Generated by Django 6.0.2 on 2026-02-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="secuenciadidactica",
            options={"verbose_name": "Secuencia Didáctica"},
        ),
        migrations.AlterField(
            model_name="secuenciadidactica",
            name="objetivo_general",
            field=models.TextField(),
        ),
    ]
