# Generated by Django 6.0.2 on 2026-02-09 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("contenido_teorico", models.TextField()),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecciones",
                        to="core.programa",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Lecciones",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Ejercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta", models.TextField()),
                (
                    "codigo_inicial",
                    models.TextField(
                        blank=True, help_text="Para cursos de programación"
                    ),
                ),
                ("solucion", models.TextField()),
                (
                    "leccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ejercicios",
                        to="cursos.leccion",
                    ),
                ),
            ],
        ),
    ]
