# Generated by Django 6.0.2 on 2026-02-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0002_inscripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="ejercicio",
            name="lenguaje",
            field=models.CharField(
                choices=[("text", "Texto"), ("python", "Python"), ("cpp", "C++")],
                default="text",
                max_length=10,
            ),
        ),
    ]
